### ISSUE TITLE
**CHECKLIST**

### ISSUE THREAD

**Issue by kieranmichaelflynn** [kieranmichaelflynn/BCKS-Project#1]
One page proposal:
1 Project title
2 Project description
3 User story
4 Wireframe/sketch of design
5 API's to be used
6 Rough task breakdown

**Comment by hergemony** [comment]
let's get started

**Comment by B-smd** [comment]
let's do it together

**Comment by hergemony** [comment]
> One page proposal: 1 Project title 2 Project description 3 User story 4 Wireframe/sketch of design 5 API's to be used 6 Rough task breakdown

1) TRAVEL & COVID

**Comment by hergemony** [comment]
3) I want to create an app that will assist me in post-Covid19 travels. I want to research cities that are open for Australian citizens. I want to check that my health status is applicable to travel to a selected destination.

**Comment by hergemony** [comment]
5) API's to be used: 
- Search engine function for destination and flights
- Health check and status API

**Comment by B-smd** [comment]
Guys thank you for editing my home page design. I just want to remain every body about the time please concentrate to finishing the Api .
